title: Kieran Porter
author: Kieran Porter
avatar: "/assets/avatar.jpg"
github_username: KieraninTehdas
navbar-links:
  About Me: "about"

social-network-links:
  email: kieranintehdas@gmail.com
  github: KieraninTehdas

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true


remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - tags
