title: KieraninTehdas
author: KP
url: "https://kieranintehdas.github.io"
github_username: kieranintehdas
avatar: "/assets/duckface.jpg"

navbar-links:
  About Me: "/about"
  Posts: "/"

social-network-links:
  email: kieranintehdas@gmail.com
  github: KieraninTehdas

# Build settings
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-feed
  - jekyll-remote-theme

show_excerpts: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
